services:
  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/helpers.sh:/helpers.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - confluent
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch  # Add this line
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}
    volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
      ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}
      xpack.security.enabled : false
      network.host: "0.0.0.0"
    networks:
      - confluent
    restart: unless-stopped

  logstash:
    container_name: elasticsearch_logstash  # Add this line
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}
    volumes:
      #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./Nginx/log/access.log:/var/log/access.log:ro,z
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}

    networks:
      - confluent
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    container_name: elasticsearch_kibana  # Add this line
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}

    volumes:
      #- ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      - ./kibana/logs:/usr/share/kibana/logs
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      ELASTIC_VERSION: ${ELASTIC_VERSION:-7.8.1}

    networks:
      - confluent
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  confluent:
    external: true  # This tells Docker Compose to use an existing network
    name: confluent
volumes:
  setup:
    driver: local
  elasticsearch:
    driver: local
  kibana:
    driver: local
